# Generated by Django 3.1.5 on 2021-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_compra', models.CharField(max_length=200)),
                ('valor_compra', models.FloatField()),
                ('entrada', models.FloatField()),
                ('data_compra', models.DateField()),
                ('tipo_parcelamento', models.IntegerField()),
                ('quantidade_parcelas', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
